### ISSUE TITLE
Where is the other translation?

### ISSUE THREAD

**Issue by inrussiawithhate** [TangoBB/TangoBB#56]
Hello, where is the other interpretation, because it's all in the file lang?
Where are the Edit Post, Close Thread ..?

**Comment by N8boy** [comment]
First of all: I'm not sure if TangoBB is still alive. I split apart from the project and opend my own project: http://ikobb.de/ but we are still in deveopment http://git.ikobb.de/.

If you really want to use TangoBB you can find the language files here: https://github.com/Codetana/TangoBB/tree/master/applications/languages

If you want to use a different language just create a new files with the same structure like the english.php file.

**Comment by inrussiawithhate** [comment]
There are many things in the topics that are not in the language pack, and with what names to add them? This is the problem.

**Comment by inrussiawithhate** [comment]
Where is Close Topic, Edit Post, etc in threads?

**Comment by N8boy** [comment]
You have manually rewrite it in the code and add it in the language files

**Comment by N8boy** [comment]
The template is, when im right, stored in the database.

**Comment by inrussiawithhate** [comment]
Problem solved. Thank you!
